# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 665218a64b096840c00f48c63500df11826d2b8b71cdd8f9caeac00f0369bba6d4e708cdd98e0b0f6e7c91828eca929f4f2fafc7c5a0bcaa8f000c8360bb8a64

test:
  secret_key_base: c8b5db1563b272b37e82d83bfb0ba345bf7788718d27bc472514e76713fe4d33c9b9f5fde9ee42d1177e52034e9d31f2beba34f4fdb07b69fdd85d4d65830909

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
